language: objective-c
xcode_sdk: iphonesimulator7.0
install:
  - brew update
  - brew install nasm
  - sudo CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments easy_install cython
  - echo '[extensions]' >> ~/.hgrc
  - echo 'purge = ' >> ~/.hgrc
script:
  - pushd dependencies
  - ./scripts/build.sh all
  - popd
  - ./tools/create-xcode-project.sh thequestion ./dependencies/tmp/renpy-6.14.1-sdk/the_question/game
  - cd app-thequestion
  - xctool
